# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='用户名', max_length=128, unique=True)),
                ('password', models.CharField(help_text='密码', max_length=256)),
                ('email', models.EmailField(help_text='邮箱', max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', help_text='性别', max_length=32)),
                ('age', models.IntegerField(help_text='年龄', null=True)),
                ('phoneNumber', models.CharField(help_text='手机号码', max_length=11, null=True)),
                ('c_time', models.DateTimeField(auto_now_add=True, help_text='注册时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-c_time'],
            },
        ),
    ]
