# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kofan', '0002_auto_20180627_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.CharField(default='default.jpg', max_length=64),
        ),
    ]
