# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kofan', '0004_auto_20180628_1448'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='ImageStore',
        ),
    ]
