# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kofan', '0005_auto_20180628_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='icon',
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
